### PR TITLE
Update website strings for Windows 11

### PR DESCRIPTION
**Pull request by jswinarton**
Based on mozilla-services/guardian-website#1380

### CODE REVIEW

**Comment by birdsarah** [comment]
@flodolo in good news, we shouldn't have the frustrations of before when localizers are working on this as all guardian front-end pages are now public. Huzzah! 

https://vpn.mozilla.org/vpn/download

**Comment by birdsarah** [comment]
Also....I did wonder whether a change like this we could just try and localize ourselves by adding the 10/11. But I didn't want to risk it. But happy to have your input.

**Comment by flodolo** [comment]
> Also....I did wonder whether a change like this we could just try and localize ourselves by adding the 10/11.

No, always better to avoid shortcuts ;-)

**Review by flodolo — APPROVED** [review]

**Comment by flodolo** [comment]
@birdsarah 
Is it OK to merge this one? Asking, since the old strings will start disappearing as soon as I do, and folks start translating the new ones.

**Comment by birdsarah** [comment]
Yes. That's great. We'll only merge and deploy on guardian side when the new strings are translated.

So please do merge this PR.

**Pull request merged**
